### ISSUE TITLE
Storing lock in /tmp folder might be a bad idea.

### ISSUE THREAD

**Issue by knopp** [oblique/named-lock#1]
/tmp gets cleaned on macOS periodically which breaks long running applications holding locks. I assume other unix platforms might have similar problem.

**Comment by knopp** [comment]
Better location to store this would be `XDG_RUNTIME_DIR` on Linux and `_CS_DARWIN_USER_CACHE_DIR` (obtained through `confstr` on macOS.

**Comment by oblique** [comment]
Other UNIX platforms do not have this issue, but I'm thinking to make this configurable.

`XDG_RUNTIME_DIR`/`_CS_DARWIN_USER_CACHE_DIR` are also bad choices because are not system-wide directories.

**Comment by knopp** [comment]
Not sure what you mean. Do other UNIX platforms not have cron jobs that clean temp folder? If you need the lock to be accessible by multiple users then indeed, `XDG_RUNTIME_DIR/_CS_DARWIN_USER_CACHE_DIR` are not good choices. I'd say that different people have different usecases so making this configurable would probably be best.

**Comment by oblique** [comment]
> Do other UNIX platforms not have cron jobs that clean temp folder?

No they don't. I'm actually surprised that MacOS has.

**Comment by knopp** [comment]
It does, but only for the /tmp folder. `$TMPDIR` (`/var/folders...`) is cleaned differently (though Apple doesn't document this anywhere).

**Comment by lpil** [comment]
I stumbled across a way to create a lock outside of `/tmp` which may be useful to you here.

Some info: https://github.com/oblique/named-lock/issues/2

**Comment by oblique** [comment]
I decided to keep `NamedLock::create` as it was before, and introduce `NamedLock::with_path`. With the new function you will be able to give the exact path of the lock file.

**Comment by oblique** [comment]
After some reading about `TMPDIR`, I decided to use it if it is set, otherwise `/tmp` will be used.

**Comment by oblique** [comment]
Version 0.2.0 is published
