### ISSUE TITLE
Lock is created outside of `/tmp` if name looks like an absolute path

### ISSUE THREAD

**Issue by lpil** [oblique/named-lock#2]
For example, if a lock is named `/one/two` the file will be created at `/one/two.lock`.

I actually think this is quite a useful behaviour, but I think it may need to be documented.

**Comment by oblique** [comment]
Nice! We can convert this bug to a feature :)

**Comment by oblique** [comment]
To keep `NamedLocked::create` cross-platform and consisted, I decided to return an error on `/` and `\` characters. But I will introduce `NamedLock::with_path` if someone wants to use a lock file outside `/tmp`.

If you have any comments on #4, let me know.

**Comment by oblique** [comment]
Version 0.2.0 is published
